### ISSUE TITLE
Mac needs updated to 64 bit

### ISSUE THREAD

**Issue by godlysparta** [133spider/AQLite#19]
Apple released a new updates that makes me unable to use the Flash Projector (because something about it being 32 bit instead of 64 bit). If you could resolve this issue, that would be great.

**Comment by 133spider** [comment]
Hi, could you try to run **aqlite.swf** using this: https://echoone.com/iswiff/ ?

**Comment by godlysparta** [comment]
I was completely unable to find SWF file. It's very different when I tried to open contents. Still unable to run AQLite. *edit again* I was able to download the electronicJS version to find the SWF. The thing only showed the loading screen.

**Comment by 133spider** [comment]
Avoid ElectronJS since performance issues became worse on it,

1.    Go here: https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html
2.    Edit Location > Add Location
3.    Put the location of the AQLite swf
"Browse for files" & "Browse for folder" do NOT work on MAC Computers. You have to manually enter the directory/path of the AQLite swf.


Download the SWF from here: https://github.com/133spider/AQLite/blob/master/aqlite.swf
Then download this flash projector below and try to run the swf file
If you can't run the flash projector below, then try to get the flash projector from Adobe's official website
[flashplayer_10_3r183_90_mac_sa.app.zip](https://github.com/133spider/AQLite/files/3774479/flashplayer_10_3r183_90_mac_sa.app.zip)

**Comment by godlysparta** [comment]
It's still frozen on the loading screen. It's either that or really slow.

**Comment by 133spider** [comment]
The three steps I posted are essential. The reason it's stuck at 0% is that you need to add the swf as a trusted location. You most likely entered the wrong directory/path to the AQLite swf.

This video below is a Windows example since I can't find an example for mac. But you'll get the idea:
https://www.youtube.com/watch?v=DOX77lpwUs4

**Comment by 133spider** [comment]
See if you can run AQLite using this: https://www.swf-flv-player.com/
Download the SWF from here: https://github.com/133spider/AQLite/blob/master/aqlite.swf

**Comment by 133spider** [comment]
Assuming solved
