### ISSUE TITLE
Game keep crashing

### ISSUE THREAD

**Issue by Letisss** [133spider/AQLite#21]
Game keep crashing with this error : adobe flash player 10.3 r183 has stopped working
Idk is it because my computer or the program plz help

**Comment by 133spider** [comment]
Can you give me more information?
What version of AQLite were you using?
What were you doing before the crash?
What were you doing at the time of the crash?
What features you have enabled?

**Comment by Letisss** [comment]
Version the lastest versions aqlite12.2
Watch this for any settings : https://youtu.be/7CijjQjV6DU
![image](https://user-images.githubusercontent.com/57785984/69225617-43a19000-0bb1-11ea-937e-51dd6433d6d4.png)

**Comment by 133spider** [comment]
It's still unknown to me of what is absolutely causing the crashing issue, but I've added a few bandages in 12.3 that may or may not fix it. I'm still tracking it down atm, but the data I have on the crashes is very limited.

**Comment by 133spider** [comment]
Hi there, it seems that I may have found the fix for the crashes. 
It seems there are issues with Flash 10 (memory management issues)
Flash 32 has better memory management than Flash 10 and so would be a solution to the crashing. However, the Flash 32 projector makes aqw stutter so you should switch to using AQLite on Firefox.
Firefox allows you to use Flash 32, while also getting rid of the stuttering issues the Flash 32 projector would give you.
[Here's a step-by-step guide](https://docs.google.com/document/d/1Uq0TFScZOCpdae6MzW7eYRbVu4ovtGM6JwucjNpoc3A/)

**Comment by 133spider** [comment]
Assuming solved
