### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by Capilla123** [133spider/AQLite#29]
It would be interesting a tool that would allow players to select the amount of drops they want to collect.

Example: I dropped 2 of a specific item, and i want 1 to use in a quest so i could select to accept only 1, and after completing the quest, accept the other one.

**Comment by jj123157** [comment]
I don't think that's possible because of how aq does drops, you can try your self using the normal client if you click no on all but one of the same stackable item and then press yes on the last one it will accept all of that item even the ones that you say no to. So strictly speaking to my knowledge this is impossible.

**Comment by 133spider** [comment]
As the user jj123157 has said, it's pretty much impossible with how the server has coded it. Though it does sound like a nice feature.
