### ISSUE TITLE
Game freeze / Constant reload

### ISSUE THREAD

**Issue by gubrus50** [133spider/AQLite#36]
![bug-picture](https://user-images.githubusercontent.com/13700080/74576391-74ac1980-4f82-11ea-9a78-e4c33f9042f7.png)

I had this bug popping up many times recently. To me, it happens only in version 13.3-Beta. So I decided to completely reinstall the whole package, and the bug still exists.

**How this bug appears**
I'm not exactly sure. But it usually happens at random when I often use the "?" button from the quest to inspect the item on my character. Then when I go back to check the other items. The game suddenly glitches.

**What do I mean by "The game suddenly glitches."**

- The buttons are suddenly toggling on and off _(Switching textures to grey and red)_ in the entity _(a character that contains the quest)_.

- When I try to teleport, nothing happens. I can't even check my own inventory because the only thing that appears on my screen are the two dark boxes as you can see in the picture.

- The overall room is being refreshed. This conclusion came from the fact that the entity _(a character that contains the quest)_ profile is constantly being reanimated and at Nulgath, once I was in the glitch mode, I couldn't attack any of the enemies, even Nulgath himself wouldn't attack me once I was moving. Also when I tried to hit any of the enemies, I received an error message in the chatbox which says "No target selected!".

**Other notes**
I've done this test at least 5 times at many NPC's. The most promising result happen to work in the /join tercessuinotlim and /join citadel. However, I couldn't recreate the same on "Try me!" button. But still, I'm worried that this feature might also be linked to the bug.

**Comment by 133spider** [comment]
Hello, rest assured I'm aware of this issue! I still appreciate you notifying me.
This issue seems to be on Adobe's side since it seems like the "ApplicationDomains" which house the item previews broke and are causing the game to break. All previous versions of AQLite are suffering from this as well. I'm trying to find a fix as we speak.

Please refrain from using them until I get out a fix:
- Quest Reward Previews
- Custom Drops UI (Clicking on an item to preview)
- Item Preview button on SBP's
- Gender button when previewing armors

**Comment by zZeroCode** [comment]
1st episode of this bug happen to me was in /akiba accessing Kotaro's Merge Shop. This bug occurred when Gender-bend functionality is also toggled.

**Comment by Marexn** [comment]
Was wondering what was going on. Lol, was about to report about of this exact issue actually, since i just got screenshots of it.
![AQW](https://user-images.githubusercontent.com/9413484/74578098-4e46a800-4f9b-11ea-9fca-1e24d70c28b5.png)
![AQW2](https://user-images.githubusercontent.com/9413484/74578110-60284b00-4f9b-11ea-9545-9a6287fb7810.png)

**Comment by gubrus50** [comment]
See once I've found the first bug, The other issue appeared which is the exact same issue that you got right now. But I've decided not to post the other issue due to the fast response of you guys.

**Comment by Marexn** [comment]
https://www.youtube.com/watch?v=DykVJl6wr_4

**Comment by 133spider** [comment]
Finally, after about 6 hours? -- I've released AQLite v13.4 to fix this critical issue
Sorry for the inconvenience this has caused you
