### ISSUE TITLE
[Question] Why does accepting drops "again" potentially lead to disconnects?

### ISSUE THREAD

**Issue by jryzkns** [133spider/AQLite#53]
First of all, kudos to you for this wonderful client, it makes running this game much more bearable.

I find that sometimes using the custom drop UI I get disconnected, and sometimes a warning pops up in the client saying that I might disconnect (and sometimes I do). I also found where this popup occurs in the code:

https://github.com/133spider/AQLite/blob/master/net/spider/draw/dEntry.as#L181

I'm not familiar w actionscript so it's a bit hard for me to decipher what's going on here. Is there a reason why this warning is there? Why ~~does the client crash if I sometimes accept drops~~ would I be disconnected if I accept drops in this case?

**Comment by 133spider** [comment]
Hello there!
This popup only shows up if you click the accept drop button more than once.
Just like with the regular dropped items, if you click the accept drop button on the same item more than once you will be disconnected. It's because when you accept a drop, you send a request to the server. Sending that same request more than once will cause you to be disconnected by the server. That's just how the game is.

This popup prevents you from disconnecting by asking if you really wanted to send the request a second time. You should ONLY click "Yes" on this popup box if you know what you're doing. Otherwise, you should always click "No" because you already accepted the drop the first time.

**Comment by jryzkns** [comment]
I see, thanks for the clarification. To double check my understanding here, when you say "click the accept drop button more than once", do you mean for the same item? like double click on the accept button? I get the idea that the game server could reject repetitive requests to prevent replay attacks. However, sometimes on a new drop I click accept (once) and the popup shows as well.

**Comment by 133spider** [comment]
Yes if you multi-click the accept button on the same drop then it will cause the box to pop up

The issue with the popup when you click the new drop could be a bug (in which I'll look into) or you're actually clicking it more than once without realizing it

**Comment by jryzkns** [comment]
I see, thanks for clarifying. I believe I am only clicking once, but I'll keep an eye out. If I come up w any leads to replicate this, I'll let you know!

**Comment by jryzkns** [comment]
Hey @133spider I have more observations

I think when I get more than one of an equip drop and I try to accept it, the warning would pop up for me. Does the custom drop UI decline duplicate equipment drops or address them in some way? An example of this would be if I was doing the Mine Crafting quest at /stalagbite and I need to accept Axe of the Prospector, which often drops multiple times. The warning pops up pretty consistently for me in this case.

Also, once the warning appears when I try to accept one drop, it pops up for every drop (even if it's not the same item) I try to accept after. Does `alreadyClicked` get reset somehow?
