### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by gubrus50** [133spider/AQLite#6]
I don't want to bother you, but I would like to know if something like: **"INSPECT item on the character"**, would ever be implemented? It is kind of annoying when you must buy the item, not knowing how it would look on your character.

**Comment by 133spider** [comment]
I've been meaning to implement this feature in, but I held off on it. Reason being, it's a bit controversial since wielding the item as a preview on your character is in kind of a "grey" area for being an OK thing to do.

However, since I know now that someone wants the feature -- expect it to be released in the next version. A "Try Me!" button in shops! The item will be equipped on your character (**in which only you can see**) for ??? (**to be determined**) seconds before being unequipped.

**Comment by 133spider** [comment]
See version 8.0 in releases tab for fulfilled request
